Design : review작성/목록 페이지 생성
sparta-USD/Na-dle-Front pull request #15
Opened 2022-11-05 03:38 UTC by hyunjooooojung

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 디자인 변경
-  [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/8-review-frontend -> main

## 변경 사항
- 음원에 대한 review를 작성하는 페이지
- 음원에 작성된 review 목록을 보여주는 페이지

## 테스트 결과
<img width="1501" alt="Screenshot 2022-11-05 at 12 38 33 PM" src="https://user-images.githubusercontent.com/113044908/200099238-83e4e7b0-fece-43c3-ba13-4e6c29c28464.png">

2022-11-05 07:59 UTC, LeeHyunji requested changes
review.html이 음원상세페이지 같은데 맞을까요?
review.html 보다는 음원상세페이지에 걸맞는 파일명으로 변경해주시면 좋을 것 같습니다!
PR 요청 타이틀도 review작성/목록 페이지보다는 음원상세페이지 로 변경해주시고, 내용이 review 내용을 적는 것이 좋을 것 같습니다!

2022-11-05 14:50 UTC, hyunjooooojung commented
네! 파일명 변경했습니다!!

2022-11-05 23:39 UTC, ssuin52 approved these changes
수정하셨군요! 고생하셨습니다~!

2022-11-07 02:37 UTC, LeeHyunji approved these changes

2022-11-07 02:40 UTC, merged