Feat: 로그인 페이지 API
sparta-USD/Na-dle-Front pull request #38
Opened 2022-11-06 18:31 UTC by kvkvd12

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] 디자인 변경
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 반영 브랜치
feature/37-signinAPI -> API

## 변경 사항
1. 로그인 API
2. (현재 로그인 url /users/api/token/) -> /users/signin/ 변경 예정
3. username, password로 로그인
4. 로그인 완료후 first_like.html 이동

## 테스트 결과
변경 사항을 설명하는데 도움이 되는 스크린샷이나 참고 자료를 추가해주세요.
![image](https://user-images.githubusercontent.com/113074549/200188524-60430cba-82ca-42ee-a18e-89db5d0bd462.png)
![image](https://user-images.githubusercontent.com/113074549/200188542-bcfc9ca2-adcd-469f-82b1-aeaaa483a2a9.png)

2022-11-06 23:28 UTC, ssuin52 approved these changes
좋습니다!!!

2022-11-07 00:22 UTC, LeeHyunji requested changes
회원가입과 동일한 error 예외처리가 필요할것 같습니다

2022-11-07 00:22 UTC, LeeHyunji commented on static/js/signin.js
> +    location.href = "http://127.0.0.1:5500/first_like.html";
이렇게 될경우 회원가입 API 연결과 마찬가지로  실제 request가 되지 않는 경우에도 로그인되었다는 alert와 메인페이지로 이동하게 됩니다.
response가 정상적으로 받아졌을 때 동작하도록 처리해야될것 같습니다.
마찬가지로 response에서 error가 발생했을대 error 메세지 처리도 필요할것 같습니다.

(참고)
```javascript
 const response = await fetch(....,{
...
})
.then(response => {
      if(!response.ok){
          throw new Error(`${response.status} 에러가 발생했습니다.`);    
      }
      return response.json()
  }).then(result => {
      alert("프로필이 수정되었습니다.")
      document.getElementById("profile_img").setAttribute("src","http://127.0.0.1:8000"+result['profile_image'])
  }).catch(error => {
      alert("프로필 수정에 실패하였습니다.\n자세한 내용은 관리자에게 문의해주세요.")
      console.warn(error.message)
  });
```

2022-11-07 00:34 UTC, kvkvd12 commented on static/js/signin.js
> +    location.href = "http://127.0.0.1:5500/first_like.html";
이것 또한 에러처리 좀 더 완벽하게 해서 올리겠습니다.

2022-11-07 10:04 UTC, merged